### ISSUE TITLE
Coverage badge

### ISSUE THREAD

**Issue by blegat** [JuliaReach/Systems.jl#11]
Any objection to add coverage badges ?

**Comment by mforets** [comment]
no objection. do you know what's the difference between "Coveralls" and "Codecov"? Or they both measure the amount of code branches that are tested but use different metrics?

**Comment by schillic** [comment]
By the way, there already is one.

**Comment by blegat** [comment]
I usually use both, they do the same thing but sometimes the interface of one is more useful. Codecov is the one better maintained and most people prefer

**Comment by mforets** [comment]
ok, thanks for the clarification. sure i have no objections to use both. any volunteer for PR? we [flip a coin](http://justflipacoin.com/)? 😄

**Comment by schillic** [comment]
I am fine with one badge. If you want more, please add them.

**Comment by blegat** [comment]
Ah yes, we already have the codecov badge, I missed that :D
