### ISSUE TITLE
Accessing X and U

### ISSUE THREAD

**Issue by blegat** [JuliaReach/Systems.jl#12]
What should be the name of the getters for `X` and `U` ?

**Comment by schillic** [comment]
Good question, I am not aware of Julian standards for getters.
* just `X` and `U` - might be confusing
* `get_X` and `get_U` - usually naming the getter like the variable name is not much better than using the field, but in this case the names are established standard
* `state_constraints` and `input_constraints` - more verbose
* ...

It could also be several of them using aliases.

**Comment by mforets** [comment]
i would upvote `state_constraints` and `input_constraints`. perhaps without the separator `_`, since this is the convention for other functions like `statedim` and `inputdim`.

**Comment by blegat** [comment]
One other option would be `stateset` and `inputset`. It reads a bit better with `x in stateset(s)` vs `x in stateconstraints(s)`. The latter seems to say that `x` is part of the constraints of `s` while it should mean that it satisfies all the constraints.

**Comment by schillic** [comment]
Going all the way, what about `states` and `inputs`?

**Comment by mforets** [comment]
i really like `stateset` and `inputset`.

**Comment by schillic** [comment]
Okay, I see that `states` and `inputs` is misleading. Then I also favor `stateset` and `inputset`.

**Comment by schillic** [comment]
The functions are missing in [the docs](https://juliareach.github.io/Systems.jl/latest/lib/methods.html).

**Comment by blegat** [comment]
I see them in the docs

**Comment by schillic** [comment]
Ha, indeed, seems that my browser had this page cached, sorry.

**Comment by blegat** [comment]
It also takes some time for the doc to be regenerated :-P
