### ISSUE TITLE
Input iterators

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Systems.jl#15]
In applications the systems can receive inputs which are constant or which vary over time. This is to propose some functionality to make defining inputs of different nature easy and efficiently within `Systems.jl`. 

(Notice that i'm not proposing to "tie" existent systems definitions with new input types.)

```julia
abstract type AbstractInput end

Base.start(::AbstractInput) = 1

# input that remains constant in time
struct ConstantInput{UT} <: AbstractInput
    U::UT
end

Base.next(inputs::ConstantInput, state) = (inputs.U, state + 1)
Base.done(inputs::ConstantInput, state) = state > 1
Base.length(inputs::ConstantInput) = 1

# add this (?)
next_input(inputs::ConstantInput, state::Int) = inputs.U
next_input(inputs::ConstantInput) = inputs.U
Base.*(M::AbstractMatrix, input::ConstantInput) =  ConstantInput(M * input.U)

# input that may vary with time
struct TimeVaryingInput{UT} <: AbstractInput
    U::AbstractVector{<:UT}  # input sequence
end

Base.next(inputs::TimeVaryingInput, state) = (inputs.U[state], state + 1)
Base.done(inputs::TimeVaryingInput, state) = state > length(inputs.U)
Base.length(inputs::TimeVaryingInput) = length(inputs.U)

# add this (?)
next_input(inputs::TimeVaryingInput, state::Int) = inputs.U[state]
```

thoughts?

**Comment by schillic** [comment]
`ConstantInput` could have a field `length`. A hard-coded length of 1 seems strange.

minor: `Int` instead of `Int64`

**Comment by mforets** [comment]
> A hard-coded length of 1 seems strange.

we know it's constant 

> minor: Int instead of Int64

done

**Comment by mforets** [comment]
> Base.*(M::AbstractMatrix, input::ConstantInput) = ConstantInput(M * input.U) should be removed. A user can add that if wanted.

agreed

**Comment by blegat** [comment]
Isn't `Base.start` is missing ?

Maybe we could say that it is infinite for constant input using
```julia
Base.iteratorsize(::ConstantInput) = IsInfinite()
```
See https://docs.julialang.org/en/stable/manual/interfaces/

**Comment by schillic** [comment]
> Isn't Base.start is missing ?

second line

**Comment by mforets** [comment]
> Maybe we could say that it is infinite

i like that idea, it reminds the graph of a constant function over time ☺️ 

thanks for your replies, i'll make the PR.
