### ISSUE TITLE
Simplify maps of constant or varying inputs

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Systems.jl#20]
I have  some code where a transformation should be applied to the input, as the one below for some function called `add_dimension`:

```julia
        # cs is a linear system x' = Ax + Bu
        if cs.s.U isa ConstantInput
            Uext = add_dimension(next(cs.s.U, 1)[1])
        elseif cs.s.U isa VaryingInput
            Uext = [add_dimension(ui) for ui in cs.s.U]
        else
            error("Unsupported inputs type $(typeof(cs.s.U)).")
        end
```

The if-else branch is needed because we cannot do list comprehension as in `[add_dimension(ui) for ui in cs.s.U]` in the case where `cs.s.U` is constant:

```julia
julia> [add_dimension(ui) for ui in cs.s.U]
ERROR: MethodError: no method matching length(::Systems.ConstantInput{LazySets.Ball2{Float64}})

Closest candidates are:
  length(::SimpleVector) at essentials.jl:256
  length(::Base.MethodList) at reflection.jl:558
  length(::MethodTable) at reflection.jl:634
  ...
Stacktrace:
 [1] _array_for at ./array.jl:462 [inlined]
 [2] collect(::Base.Generator{Systems.ConstantInput{LazySets.Ball2{Float64}},#add_dimension}) at ./array.jl:476
```

This is on purpose because the constant input is an abstraction for an infinite-dimensional list. 

That said, i wonder if there is a workaround allowing to simplify this if-else clause, perhaps overloading some function in Base such as `map(add_dimension, cs.s.U)`.

**Comment by schillic** [comment]
`isa` chains are not good in Julia. Better define a function `add_dimension(u::U)` for each type of input `U`. But this still requires these different lines implementations. Is your motivation to save lines of code?

**Comment by mforets** [comment]
i had a further look and the code snippet of above is equivalent to  `map(add_dimension, inputset(cs))` irrespective if `U` is constant or varying, if we let:

``` julia
import Base.map
map(f::F, c::ConstantInput) where F = ConstantInput(f(next(c, 1)[1]))
```

**Comment by blegat** [comment]
It would make sense to have it, I would simply do
```julia
Base.map(f::Function, c::ConstantInput) = ConstantInput(f(c.U))
```
