### ISSUE TITLE
Revise map function

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Systems.jl#23]
Suppose that given some inputs you want to apply the function `norm(x, Inf)` to each element, eg.:

```julia
julia> c = ConstantInput(ones(2))
Systems.ConstantInput{Array{Float64,1}}([0.0, 0.0])

julia> map(x->norm(x, Inf), c)
Systems.ConstantInput{Float64}(1.0)

julia> @which map(x->norm(x, Inf), c)
map(f::Function, c::Systems.ConstantInput) in Systems at /Users/forets/.julia/v0.6/Systems/src/inputs.jl:81
```

This has used our `map` function which generates a new object of type `ConstantInput` where you apply the function `norm` elementwise.

For varying inputs the procedure of above fails:

```julia
julia> v = VaryingInput([zeros(2), ones(2)])
Systems.VaryingInput{Array{Float64,1}}(Array{Float64,1}[[0.0, 0.0], [1.0, 1.0]])

julia> map(x->norm(x, Inf), v)
ERROR: MethodError: Cannot `convert` an object of type Float64 to an object of type Systems.VaryingInput
This may have arisen from a call to the constructor Systems.VaryingInput(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] Systems.VaryingInput(::Float64) at ./sysimg.jl:77
 [2] map(::##83#84, ::Systems.VaryingInput{Array{Float64,1}}) at /Users/forets/.julia/v0.6/Systems/src/inputs.jl:199
```

I think this is because we should use dot syntax to broadcast the `norm` operation,

```julia
Base.map(f::Function, v::VaryingInput) = VaryingInput(f.(v.U))
```

**Comment by mforets** [comment]
Ah, well, one can just do `map(x->norm.(x, Inf), v)` ..

**Comment by schillic** [comment]
Not being helpful here:
The question is whether the user should know these implementation details.
On the other hand, will broadcast make sense in all cases?

**Comment by mforets** [comment]
for example if i use Base's `map` the broadcast is done internally,

```julia
julia> v = [zeros(2), ones(2)]
2-element Array{Array{Float64,1},1}:
 [0.0, 0.0]
 [1.0, 1.0]

julia> map(x->norm(x, Inf), v)
2-element Array{Float64,1}:
 0.0
 1.0
```

**Comment by mforets** [comment]
> On the other hand, will broadcast make sense in all cases?

the existent tests work and i've added the new one.
