### ISSUE TITLE
Continuous vs. discrete systems

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Systems.jl#5]
As far as I can see, the continuous and discrete system definitions are identical up to the comments. Is there actually a reason why a system description has to differentiate between continuous and discrete? This could be up to the interpretation of the user.

The only benefit I see (are there more?) is that one can write generic code for `AbstractSystem` and then switch based on the type. But this can also be done by passing a flag. I am not sure if this really justifies the duplication overhead.

**Comment by mforets** [comment]
for background, in [Reachability.jl](https://github.com/JuliaReach/Reachability.jl/blob/master/src/Systems/Systems.jl#L308) the only difference was having a step size field `δ` just for convenience of the discrete case. then, we used the type as information eg. "discretizing" functions `ContinuousSystem->DiscreteSystem`. 

it's true that the provided types can be interpreted in many different ways, eg. a `LinearContinuousSystem` could mean for the user `x'' = Ax`.

**Comment by blegat** [comment]
It seems to me that it is better if the system are fully defined by their type + field values. We could do
```
struct LinearSystem{C}
...
end
const LinearContinuousSystem = LinearSystem{true}
const LinearDiscreteSystem = LinearSystem{false}
```
to avoid duplication.

**Comment by schillic** [comment]
I have mixed feelings about a type parameter because this will not be as easy if there are more parameters, right?

I am fine with keeping it the way it is. (close?)

**Comment by mforets** [comment]
ok, seems like the consensus is to move on as is now, we can eventually rethink depending on what usage arises..
